generator/rust.stoneg.py, src/generated/file_properties.rs, src/generated/files.rs
1. File-scope doc comments (those starting with "//!") that refer to
types defined in the module need to have the link include the name of
the module, or rustdoc can't resolve the reference.
2. References to routes in another namespace were being generated with
multiple "super::" components in their path; instead, the human-visible
name should just be "namespace::route", and the link path needs to be
fixed to just "super::namespace::route".
=> some documentation formatting fixes

examples/demo.rs
As written, the list_directories function in demo.rs could not be used
to list anything but the root directory. I stumpled upon this while
doing my own experimentation and copy & pasting code together from the
demo.
The fix is easy: if '/' is requested, query the empty string, otherwise
query the string as passed by the caller.
=> [examples/demo] Fix bug in list_directory with non-root path

examples/demo.rs
If the first request for `list_folder` returned all entries, the `demo.rs` program will still do another request since it does not check `has_more` in the initial reply. This fixes this.
=> Avoid unnecessary roundtrip in list_directory.

examples/demo.rs
1. somehow the buffering inside a loop appears to cause a stack overflow on Windows. Replacing this with a call to `std::io::copy` fixes the issue (maybe by moving the buffer to another stack frame?), and is IMO more readable anyway.
2. having demo download a file that's not there will cause it to loop forever. The retry loop should default to breaking out at the end unless there's a read error.
=> a couple small fixes to examples/demo

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question_help.md, .github/dependabot.yml, .github/pull_request_template.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
This makes the SDK look at bit more like the official SDK-related repos. See
* https://github.com/dropbox/dropbox-sdk-python
* https://github.com/dropbox/dropbox-sdk-dotnet
* https://github.com/dropbox/stone
We can also set up a workflow to automatically update the spec / create PRs if someone is able to regularly merge them.
=> Bring rust SDK more in line with recent SDK quality improvements

README.md, RELEASE_NOTES.md, examples/demo.rs, examples/large-file-upload.rs, generator/rust.stoneg.py, src/client_helpers.rs, src/client_trait.rs, src/generated/account.rs, src/generated/auth.rs, src/generated/check.rs, src/generated/contacts.rs, src/generated/file_properties.rs, src/generated/file_requests.rs, src/generated/files.rs, src/generated/paper.rs, src/generated/sharing.rs, src/generated/team.rs, src/generated/users.rs, src/hyper_client.rs, src/lib.rs, src/oauth2.rs
**Is This a Code Change?**
This implements different authentication types in the default Hyper client, and changes the client trait so that custom clients can do so as well. Previously, the Hyper client only did User auth, and the single client trait meant that API calls which require specific authentication types could not ensure they are only called by a capable client.
This change adds three new marker traits which require the general HttpClient trait, and indicate that a client is capable of User auth, Team auth, or unauthenticated access. API functions then require the appropriate type of client. Additionally, the Team auth mode allows specifying User or Admin context.
Finally, as a bit of a drive-by fix, but nice to do as long as I'm doing major changes to …
=> Implement authenticaiton types (User/Team/Noauth) and general overhaul of the HTTP client code.

src/hyper_client.rs
**Is This a Code Change?**
Forward fix for a bug in #16 so that you can actually use `NoauthHyperClient` with the `files::list_folder_longpoll` function as intended.
=> NoauthHyperClient needs to implement NoauthClient trait

Cargo.toml, RELEASE_NOTES.md, src/client_helpers.rs, src/lib.rs
Also while we're at it, stop doing manual `Deserialize` derives for the error structs. proc-macro2, quote, and syn are already pulled in by thiserror, so this doesn't actually impact our dependency tree. Having one manually-written implementation (for TopLevelError) wasn't bad, but now there's three of them that can use this.
The SDK types have manual implementations for Deserialize because of some aspects of Dropbox's serialization style which serde doesn't completely support, but these error types don't appear to ever hit those corner cases, so a derived implementation works fine.
**Validation**
Ran the examples and verified that they still work. Furthermore, an integration test I'm currently working on exercises this by making a lot of upload calls, which gets …
=> change Error::RateLimited to show the reason and the retry time

generator/rust.stoneg.py, src/generated/file_properties.rs, src/generated/file_requests.rs, src/generated/files.rs, src/generated/paper.rs, src/generated/sharing.rs, src/generated/team.rs
If a default value contains no parenthesis, consider it "trivial" and emit it directly in a `.unwrap_or()` instead of in a closure with `.unwrap_or_else()`.
Otherwise, Clippy (on current nightly) warns of `unnecessary_lazy_evaluations` in these cases.
Unfortunately, Clippy has type information at its disposal and we do not, but this rough heuristic appears to be good enough.
**Validation**
Clippy (nightly) now passes for all targets; serialize/deserialize tests still pass. Manually inspected the handful of lines this changed.
=> avoid closures for default values in some cases

.github/pull_request_template.md
The code change type section isn't very helpful and results in a
checklist for every PR that will never get to 100%.
Additionally, adding some examples of what we're looking for in the
Validation section. (I imagine this section to be similar to the Test
Plan section of Dropbox's Phabricator diffs.)
**Is This a Code Change?**
**Validation**
N/A: Purely repository metadata.
=> remove code change type section from the pull request template

Cargo.toml, tests/benchmark.rs, tests/common/mod.rs, tests/list_folder_recursive.rs
list_folder_recursive: creates folders, deletes folders, uploads files,
lists folders recursively, and uses list_folder_continue with a cursor
fetch_files: uploads 100 1MiB files, then times how quickly it can
download them.
Requires an environment variable DBX_OAUTH_TOKEN be set in order to
function.  Both tests are marked #[ignore] because they're time
consuming to run, require network connectivity, an auth token, and so
they should probably only be run manually.
To run them, run `cargo test -- --ignored --nocapture <test name>`
**Validation**
These *are* the tests :)
=> add two integration tests

RELEASE_NOTES.md, examples/large-file-upload.rs, generator/rust.stoneg.py, src/generated/account.rs, src/generated/auth.rs, src/generated/check.rs, src/generated/common.rs, src/generated/contacts.rs, src/generated/dbx_async.rs, src/generated/file_properties.rs, src/generated/file_requests.rs, src/generated/files.rs, src/generated/paper.rs, src/generated/secondary_emails.rs, src/generated/sharing.rs, src/generated/team.rs, src/generated/team_common.rs, src/generated/team_policies.rs, src/generated/users.rs, tests/list_folder_recursive.rs
This concerns builder methods on structs, the `fn with_fieldname(mut self, value: ...) -> Self` methods that let you change a field, and can be chained together as an expression.
Two changes:
1. Structs which have no required fields, but only optional fields, were not having any builder methods emitted at all, because the logic to skip emitting a constructor skipped the whole `impl` block. This affects a relatively low number of structs and is completely backwards compatible, as it's only adding methods.
2. Change builder methods for optional fields (i.e. whose type is `Option<T>`) to take the value type `T` as an argument directly. The rationale for this change is that optional fields always have `None` as their default value, so there's practically no reason to call builder methods to …
=> improvements to builder methods on structs

RELEASE_NOTES.md, generator/rust.stoneg.py, generator/test.stoneg.py, src/generated/account.rs, src/generated/auth.rs, src/generated/check.rs, src/generated/common.rs, src/generated/contacts.rs, src/generated/dbx_async.rs, src/generated/file_properties.rs, src/generated/file_requests.rs, src/generated/files.rs, src/generated/paper.rs, src/generated/secondary_emails.rs, src/generated/seen_state.rs, src/generated/sharing.rs, src/generated/team.rs, src/generated/team_common.rs, src/generated/team_policies.rs, src/generated/users.rs, src/generated/users_common.rs
In addition to `Debug`. These traits are useful in many situations and can safely be implemented for every type in the SDK because they are essentially POD (plain old data) types and we have no private fields or special logic assigned to them.
It would be nice to implement `Eq` and `Hash`, but these can't be derived for types containing `f64`, of which there are a few in the SDK. We could implement them for types not containing these fields, but for the sake of forwards-compatibility, it's better to stick with the minimum set that can be implemented for every type.
**Validation**
All tests now include an `assert_eq!` check that a `clone()` of the instance matches the original instance, which exercises both `PartialEq` and `Clone` traits.
Tests for serializable …
=> derive Clone and PartialEq for every type

RELEASE_NOTES.md, generator/rust.py, generator/rust.stoneg.py, generator/test.stoneg.py, src/client_helpers.rs, src/generated/account.rs, src/generated/auth.rs, src/generated/check.rs, src/generated/common.rs, src/generated/contacts.rs, src/generated/dbx_async.rs, src/generated/file_properties.rs, src/generated/file_requests.rs, src/generated/files.rs, src/generated/paper.rs, src/generated/sharing.rs, src/generated/team.rs, src/generated/users.rs, src/lib.rs
In general, this change makes many types that are used as errors, look more like proper error types in Rust.
The impl of `std::error::Error` has been improved to no longer include the deprecated `description()` method, and to include a `source()` method that returns any inner value if that value is also an error type.
The `Display` impl of these has been improved to make use of the types' documentation as much as possible, falling back to `Debug` representation when none is available. This replaces the current behavior, where the `Debug` representation is always re-used for `Display`.
The quality of these error messages varies a bit, as they were not always written with the intent to be used as display messages, but the vast majority are quite good.
As a breaking change, the error type …
=> Several improvements to error types

Cargo.toml, README.md, RELEASE_NOTES.md, src/default_client.rs
While this is a major-version change to an important dependency, this is all hidden behind the `HttpClient` facade and none of it leaks out to users.
Therefore there should be no user-visible changes unless you really care about the TLS implementation, which has changed from platform-native TLS to `rustls`.
And of course, if you're not using `default_client` this has no effect whatsoever. :)
**Validation**
Covered by existing integration tests.
=> update to ureq 2.0.0

RELEASE_NOTES.md, generator/rust.stoneg.py, src/generated/account.rs, src/generated/auth.rs, src/generated/common.rs, src/generated/contacts.rs, src/generated/dbx_async.rs, src/generated/file_properties.rs, src/generated/file_requests.rs, src/generated/files.rs, src/generated/paper.rs, src/generated/seen_state.rs, src/generated/sharing.rs, src/generated/team.rs, src/generated/team_common.rs, src/generated/team_policies.rs, src/generated/users.rs, src/generated/users_common.rs, tests/compatibility.rs
Avoid repeating eat_json_fields for all nullary variants and just do it at the end to consume any fields not recognized by inner deserializers.
This results in a net of 5161 lines removed.
**Validation**
Automated tests. Also added another case to the compatibility tests (which passed before, and still passes).
=> make deserializer for unions more concise

src/client_helpers.rs
Not all 429 errors have this field: `too_many_write_operations` isn't a time-based limit, so it doesn't include it. Currently, encountering this results in `Error::Json` instead of `Error::RateLimited` due to serialization failure in client_helpers.
We could change it to `Optional<u32>`, but that would be a breaking change; instead, default to 0.
It should hopefully be clear from a value of zero that the request can be retried immediately, as long as you're under the limit on concurrent operations.
**Validation**
I originally hit this when running the integration tests repeatedly, so that's a good test right there.
=> give retry_after field in 429 responses a default value

examples/large-file-upload.rs
Rather than thrashing and quickly erroring out, do the delay requested by the server.
**Validation**
Hit this myself when using it to upload some large backup files, so I tested it manually. This is example code; doesn't need automated testing beyond that.
=> examples/large-file-upload: honor the retry-after field when rate-limited

examples/large-file-upload.rs
Because we upload blocks in parallel, we may hit an error on a block but still upload some blocks after that one. Then when resuming, we can hit an error when the API complains that we already have data at an offset we're trying to upload to. If we're resuming, assume that this is fine and keep going.
(Ideally the API would see that the data in question matches the already-uploaded block and not raise this error, but it doesn't...)
Additional resume-related drive-by fixes:
* use the resume start offset to print the correct percentage uploaded of the whole file (papercut)
* adjust additions to the completion map by the resume start offset (actual bugfix)
**Validation**
Hit this myself when using it to upload some large backup files, so I tested it manually. This is …
=> examples/large-file-upload: ignore reuploaded block errors when resuming

RELEASE_NOTES.md, generator/rust.stoneg.py, generator/test.stoneg.py, src/generated/account.rs, src/generated/auth.rs, src/generated/check.rs, src/generated/common.rs, src/generated/contacts.rs, src/generated/dbx_async.rs, src/generated/file_properties.rs, src/generated/file_requests.rs, src/generated/files.rs, src/generated/paper.rs, src/generated/secondary_emails.rs, src/generated/sharing.rs, src/generated/team.rs, src/generated/team_common.rs, src/generated/team_policies.rs, src/generated/users.rs
This changes how structs with optional fields are serialized. Previously, fields whose value was set to `None` were serialized in the JSON as `null`. This works, but is unnecessarily verbose, but the bigger deal is that it isn't accepted by our deserializer code.
With this change, we skip writing these fields entirely.
Now, we could fix the deserializers to accept `null` for `Option` fields, but for now let's just stop using `null` entirely. We can always add that support later if there's a good reason to.
This also beefs up the tests by adding test cases for structs which omit all the optional fields, which is how I verified this works correctly. These tests will also be good for catching compatibility issues in the future.
**Validation**
test change included
=> Skip serializing struct fields whose values are `None`

generator/rust.stoneg.py, src/client_trait.rs, src/default_client.rs, src/generated/account.rs, src/generated/auth.rs, src/generated/check.rs, src/generated/common.rs, src/generated/contacts.rs, src/generated/dbx_async.rs, src/generated/file_properties.rs, src/generated/file_requests.rs, src/generated/files.rs, src/generated/paper.rs, src/generated/secondary_emails.rs, src/generated/seen_state.rs, src/generated/sharing.rs, src/generated/team.rs, src/generated/team_common.rs, src/generated/team_policies.rs, src/generated/users.rs, src/generated/users_common.rs
This adds an `Eq` trait derive for most types (anything not containing an f32 or f64).
**Validation**
Existing automated tests.
=> fix some clippy lints

.github/workflows/cargo-test.yml, Cargo.toml, RELEASE_NOTES.md, clippy.toml, examples/demo.rs, tests/noop_client.rs
I used `cargo-msrv` to figure out what the current oldest rustc able to compile the project is, and it's 1.56.1, from October 2021. Going forward, I think it'd be good to ensure this is buildable using a Rust toolchain that's at least a year old.
This is motivated by Clippy adding lints for things that are only supported on fairly recent Rust. (In this case, it's inline variables in format strings.) We can disable those lints by adding a MSRV. Also it's just a good practice in general to be up-front about compiler support.
**Validation**
I changed the GitHub tests to use the MSRV rust instead of the current Stable rust.
=> Establish a MSRV (minimum supported Rust version)

Cargo.toml, RELEASE_NOTES.md, examples/demo.rs, generator/test.stoneg.py, src/lib.rs
The test generator uses some internals of Python's regex module which got renamed in Python 3.11. Ideally we'd not use this, as apparently it's supposed to be private and may eventually get removed, but replacing it is not trivial and it's pretty important functionality, so for now just adapt to the new name and cross our fingers that it stays around.
While I'm at it, I updated the Stone SDK submodule (it hasn't been updated in a long time), and fixed a couple Clippy lints.
**Validation**
Test generator works now, and tests pass.
=> Fixes for Python 3.11

RELEASE_NOTES.md, generator/rust.stoneg.py, generator/test.stoneg.py, src/generated/auth.rs, src/generated/check.rs, src/generated/common.rs, src/generated/file_properties.rs, src/generated/file_requests.rs, src/generated/files.rs, src/generated/openid.rs, src/generated/paper.rs, src/generated/sharing.rs, src/generated/team.rs, src/generated/team_common.rs, src/generated/users.rs, tests/compatibility.rs, tests/json.rs
Four related parts to this change:
First, while structs already omit fields which are null while serializing, but I noticed that the polymorphic struct serializer (used for things like files::Metadata) did not. This changes those to call the logic in their inner structs to do so.
Second, while we skipped nulls, we can also skip non-nullable fields if they are set to the default value for the field.
Third, though the polymorphic struct serializer wrote json with nulls, the deserializer actually couldn't handle them. In practice this won't matter much because the actual Dropbox server backend doesn't do this, but it's still valid json so we should handle it.
Finally, this identified a gap in the automated testing: polymorphic structs did not have tests for their no-optional-fields case. …
=> Omit default values and nulls when serializing, accept nulls when deserializing

RELEASE_NOTES.md, generator/rust.stoneg.py, src/generated/common.rs, src/generated/dbx_async.rs, src/generated/file_properties.rs, src/generated/file_requests.rs, src/generated/files.rs, src/generated/paper.rs, src/generated/sharing.rs, src/generated/team.rs, src/generated/users.rs
Fixes #128.
For structs, `extends` means the subtype adds additional fields, so we can implement `From` to upcast from the subtype to the supertype.
For unions, `extends` means the subtype adds additional variants, so we can implement `From` to downcast from the supertype to the subtype.
For polymorphic structs, `extends` is for the inner data type of variants, so we can implement `From` on the subtype to return the correct variant of the parent type.
This solves some common problems, such as `files::UploadArg` which extends `files::CommitInfo`: they have nearly the same fields and are used together usually, so being able to convert from one to the other is useful.
**Validation**
No tests for this specifically. Just having it compile is good enough for this IMO.
=> model the 'extends' relationship using From/Into

generator/test.stoneg.py
When generating the OnlyRequiredFields tests, we need to check that the implicit defaults (the omitted fields in the JSON) were deserialized to the expected value, whether None or an other specified default value.
This means we have to still generate TestField instances for these fields, since that's what's responsible for emitting the assertions.
**Validation**
This is an improvement to the tests.
=> generated tests: emit assertions for implicit default values

examples/large-file-upload.rs
Replace it with `DateTime::from_timestamp`.
**Validation**
it builds, clippy no longer complains
=> replace deprecated NaiveDateTime::from_timestamp_opt

src/oauth2.rs
It's useful if you're using oauth2::get_auth_from_env_or_prompt where there isn't otherwise a way to get the client ID the user entered.
=> make Authorization::client_id public

src/oauth2.rs
The purpose of this change is to support the following scenario:
I am writing an app to be as scriptable (non-directly-interactive) as possible. When doing the PKCE auth procedure, it outputs the auth URL and terminates. The user can go to the URL, get the password, and invoke my app again later with this information to finish the procedure.
However, this requires that my app save the PKCE code somewhere between invocations. It's just a string so it's easy to store. The problem is, dropbox-sdk has chosen to wrap it in a single field struct where the code is private, there aren't any setters or getters, and it can't be constructed with a provided value, so I can't get the code out (or back in) by any safe means. Therefore my app currently uses unsafe rust (transmute) to make the code …
=> make pkcecode string pub to support serialization

Cargo.toml, generator/rust.stoneg.py, src/generated/mod.rs, src/lib.rs, src/oauth2.rs
In particular, don't show that feature on docs.rs, it clutters it too much.
This doesn't affect what gets reexported where, just how it looks in docs.
**Validation**
`cargo +nightly rustdoc --all-features -- --cfg docsrs`
=> rename sync_routes_default feature to sync_routes_in_root and improve docs around that

README.md, RELEASE_NOTES.md, src/async_client_trait.rs, src/client_trait.rs, src/default_async_client.rs, src/default_client.rs, src/lib.rs, tests/async_client_test.rs, tests/noop_client.rs, tests/sync_client_test.rs
With the v0.19 HTTP client refactor, implementing this was super easy.
Resolves #156 
**Validation**
Tested manually with the `check/app` route.
=> Add implementation of AppAuthClient for default (sync & async) clients.

Cargo.toml, src/oauth2.rs
There's a replacement in std that requires 1.70 which is old enough for us.
**Validation**
it builds
=> remove unmaintained atty crate from dependencies

generator/rust.stoneg.py, src/generated/async_routes/files.rs, src/generated/async_routes/sharing.rs, src/generated/async_routes/team.rs, src/generated/sync_routes/files.rs, src/generated/sync_routes/sharing.rs, src/generated/sync_routes/team.rs, src/generated/types/common.rs, src/generated/types/dbx_async.rs, src/generated/types/file_properties.rs, src/generated/types/files.rs, src/generated/types/paper.rs, src/generated/types/sharing.rs, src/generated/types/team.rs, src/generated/types/users.rs
This uses the shorthand for links to things already in scope. It shortens the generated code a bit and makes it easier to read.
**Validation**
CI
=> remove redundant intra-doc link targets from generated doc comments

.git-blame-ignore-revs, .github/workflows/cargo-test.yml, examples/demo-async.rs, examples/demo.rs, examples/large-file-upload.rs, src/async_client_trait.rs, src/client_helpers.rs, src/client_trait.rs, src/error.rs, src/lib.rs, src/oauth2.rs, tests/async_client_test.rs, tests/benchmark.rs, tests/common/mod.rs, tests/json.rs, tests/list_folder_recursive.rs, tests/noop_client.rs, tests/path_root.rs, tests/sync_client_test.rs
I personally disagree with several of rustfmt's decisions, but it's better to be consistent.
Generated code isn't being formatted because
1) it would have to get reformatted every time it gets generated; I'm
not going to make the generator emit it so it matches rustfmt
2) rustfmt currently chokes on some of the generated code
**Validation**
existing automated tests
=> rustfmt everything except generated code

.github/workflows/cargo-test.yml, src/async_client_trait.rs, src/client_helpers.rs, src/client_trait.rs, src/lib.rs, tests/generated_tests.rs
Misc small documentation and code readability fixes.
**Validation**
existing tests; no functionality is changed
=>  Misc small documentation and code readability fixes.

.github/workflows/cargo-test.yml, src/default_async_client.rs, src/default_client.rs
rustfmt has a known limitation (https://github.com/rust-lang/rustfmt/issues/3253) that modules declared inside macros are not processed when using 'cargo fmt'. So instead, let's brute-force 'find' all applicable rust sources and call rustfmt directly.
**Validation**
review
=> rustfmt modules included from if_feature! macro

Cargo.toml, RELEASE_NOTES.md, src/default_client.rs
**Validation**
Ran existing integration tests and did some manual testing.
=> upgrade ureq to v3.0

generator/rust.stoneg.py, src/generated/types/account.rs, src/generated/types/auth.rs, src/generated/types/common.rs, src/generated/types/contacts.rs, src/generated/types/dbx_async.rs, src/generated/types/file_properties.rs, src/generated/types/file_requests.rs, src/generated/types/files.rs, src/generated/types/openid.rs, src/generated/types/paper.rs, src/generated/types/seen_state.rs, src/generated/types/sharing.rs, src/generated/types/team.rs, src/generated/types/team_common.rs, src/generated/types/team_policies.rs, src/generated/types/users.rs, src/generated/types/users_common.rs
Testing out the Rust 2024 edition revealed some cases where the generated serialization code is inconsistent in its binding modes. We start as ref (`&self`), switch to move (using `*` deref operator), then back to ref (using `ref`). The 2024 edition doesn't let you do this, and we don't need to anyway (just stay in ref mode), so let's fix that.
**Validation**
Everything compiles.
=> correct some inconsistent match bindings

.github/workflows/cargo-test.yml, generator/rust.stoneg.py, src/default_async_client.rs, src/generated/types/file_properties.rs, src/generated/types/files.rs, src/generated/types/openid.rs, src/generated/types/paper.rs, src/generated/types/sharing.rs, src/generated/types/team.rs
Otherwise, with nested errors, you can end up with unhelpful errors like this (example printed by `anyhow`):
```
Error: failed to get metadata for "/temp/spoopadoop"
Caused by:
0: Dropbox API endpoint returned an error: There is nothing at the given path.
1: There is nothing at the given path.
2: There is nothing at the given path.
```
instead, with this change, you get:
```
Error: failed to get metadata for "/temp/spoopadoop"
Caused by:
0: Dropbox API endpoint returned an error: GetMetadataError: There is nothing at the given path.
1: GetMetadataError: There is nothing at the given path.
2: There is nothing at the given path.
```
which is less repetitive and gives a better indication of what actually went wrong.
**Validation**
This affects display of errors only; …
=> use type name in Display impl for errors with no other message set
