dropbox/dropbox-sdk-rust

- .github/workflows/cargo-test.yml
Very basic, just generates tests & runs cargo test.
> GitHub actions

- .github/workflows/cargo-test.yml
- examples/demo.rs
- examples/large-file-upload.rs
also fix clippy lints in the examples, which is what motivated this in the first place
>  [GitHub Actions] run clippy and check that generated files are checked in

- RELEASE_NOTES.md
- src/generated/files.rs
- src/generated/sharing.rs
- src/generated/team_policies.rs
**Is This a Code Change?**
No changes other than generated code and release notes. Very small API update.
> update API spec and Stone submodule

- Cargo.toml
- examples/demo.rs
- examples/large-file-upload.rs
In particular, this significantly cleans up the `large-file-upload` example, and upgrades it to upload blocks in parallel, making use of the new API for that 😎 
**Validation**
This only affects example code.
> Overhaul the examples

- RELEASE_NOTES.md
- src/generated/common.rs
Semver compatible update.
**Validation**
API spec update only, covered by generated tests.
> API spec updates 2020-12-03 and 2020-11-12

- src/lib.rs
Checked with api-platform, and verified that routes which have Void as an error type cannot return HTTP 409 Conflict at all, so there's no reason to have any value of this type ever.
This would be a breaking change, but the original NoError type isn't part of any release yet.
**Validation**
existing tests pass & clippy is happy
> change NoError to an uninhabited type

- RELEASE_NOTES.md
- src/generated/files.rs
- src/generated/team.rs
three spec updates, one of which contains a small breaking change (required struct field being changed to optional), necessitating minor version bump
**Validation**
automated tests are fine, and in fact caught the breaking change automatically 🎉
> Spec updates up to 2021-02-10

- RELEASE_NOTES.md
- generator/test.stoneg.py
- src/default_client.rs
- src/generated/team.rs
team_log and documentation
**Validation**
generated tests
> API spec update 2021-03-24

- RELEASE_NOTES.md
- src/generated/sharing.rs
- src/generated/team.rs
Automated tests indicate this is backwards-compatible.
**Validation**
> two API spec updates: 2021-04-14 and 2021-04-08

- RELEASE_NOTES.md
- src/generated/team.rs
https://github.com/dropbox/dropbox-api-spec/pull/39
**Validation**
passes all generated tests; semver compatible as well
> API spec update 2021-05-07

- examples/large-file-upload.rs
Do it in such a way that better enables resumes on errors.
Also, the "different contents" code was in error, I think, so removing
that.
**Validation**
> examples/large-file-upload: better session-closing logic

- RELEASE_NOTES.md
- src/generated/files.rs
**Validation**
generated tests
> spec updates though 2021-09-29

- RELEASE_NOTES.md
- src/generated/files.rs
- src/generated/team_policies.rs
**Validation**
automated tests
> spec updates thru 2021-11-17

- .github/workflows/cargo-test.yml
- RELEASE_NOTES.md
- generator/rust.stoneg.py
- src/client_helpers.rs
- src/generated/check.rs
- src/generated/files.rs
- src/generated/paper.rs
- src/generated/sharing.rs
- src/generated/team.rs
- src/generated/team_common.rs
This changes the clippy tests to use the nightly toolchain, in the hopes of catching things earlier.
Along the way, it fixes some new lints that haven't made it to stable yet. See individual commit messages for details.
**Validation**
For `Default` derive, I inspected the changes manually. Only a small handful of non-trivial impls remain now.
> Fix some new clippy lints

- RELEASE_NOTES.md
- src/generated/sharing.rs
- src/generated/team_policies.rs
**Validation**
automated tests
> spec update 2021-12-01

- examples/demo.rs
- generator/rust.stoneg.py
- src/default_client.rs
- src/generated/check.rs
- src/oauth2.rs
**Validation**
existing tests; no functionality changed
> fix a couple new clippy lints

- RELEASE_NOTES.md
- src/generated/files.rs
- src/generated/sharing.rs
**Validation**
Automated tests indicate this is semver-compatible.
> spec update 2022-02-02

- .github/dependabot.yml
- .github/workflows/cargo-test.yml
> bump actions/checkout, actions/setup-python, and make dependabot less noisy

- generate.py
Fixes the following warning:
`generate.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses`
**Validation**
No change to generated code, and all tests pass.
> replace deprecated python imp module with importlib

- RELEASE_NOTES.md
- src/generated/files.rs
Semver-compatible spec update.
**Validation**
Generated tests.
> spec update 2022-06-15

- RELEASE_NOTES.md
- examples/large-file-upload.rs
- src/generated/sharing.rs
- src/generated/team.rs
**Validation**
Automated tests. This change is not semver-compatible according to the tests (`team::TeamGetInfoResult` has a new non-optional field) but I haven't cut a new version since last time so it doesn't matter and can just be folded in to 0.16 also.
> spec update 2022-11-09

- .github/workflows/cargo-test.yml
- Cargo.toml
This is still >1 year old, and allows updating some of our dependencies.
**Validation**
Automated tests.
> bump MSRV to 1.57.0

- Cargo.toml
- src/oauth2.rs
Some breaking changes to this crate required manual fixing.
**Validation**
Automated tests.
> upgrade base64 to 0.21

- RELEASE_NOTES.md
- generator/test.stoneg.py
- src/generated/auth.rs
- src/generated/check.rs
- src/generated/file_requests.rs
- src/generated/files.rs
- src/generated/sharing.rs
- src/generated/team.rs
- src/generated/team_policies.rs
Not sure how I missed this one, whoops.
A couple unfortunate semver breakages here, due to required `shared_folder_link_restriction_policy` fields being added to some structs.
**Validation**
Generated tests. Test gen also needed a fix for Unregex because file_tagging/TagText type's regex was changed to include a `\w` category which it never had to handle before.
> spec update 2023-04-26

- .github/workflows/cargo-test.yml
It removed some long-deprecated python packages.
**Validation**
existing tests
> update stone sdk
